"""add phase 3 constraints, indexes, report notes and links

Revision ID: c981823b5a88
Revises: 5b200b8697f8
Create Date: 2026-09-05 11:26:09.612688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c981823b5a88'
down_revision: Union[str, Sequence[str], None] = '5b200b8697f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_members_user_project', 'project_members', ['user_id', 'project_id'])
    op.create_unique_constraint('uq_report_versions_report_number', 'report_versions', ['report_id', 'version_number'])
    op.add_column('weekly_reports', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('weekly_reports', sa.Column('links', sa.Text(), nullable=True))
    op.create_index('ix_weekly_reports_status', 'weekly_reports', ['status'], unique=False)
    op.create_index('ix_weekly_reports_week_start', 'weekly_reports', ['week_start'], unique=False)
    op.create_unique_constraint('uq_weekly_reports_user_week', 'weekly_reports', ['user_id', 'week_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weekly_reports_user_week', 'weekly_reports', type_='unique')
    op.drop_index('ix_weekly_reports_week_start', table_name='weekly_reports')
    op.drop_index('ix_weekly_reports_status', table_name='weekly_reports')
    op.drop_column('weekly_reports', 'links')
    op.drop_column('weekly_reports', 'notes')
    op.drop_constraint('uq_report_versions_report_number', 'report_versions', type_='unique')
    op.drop_constraint('uq_project_members_user_project', 'project_members', type_='unique')
    # ### end Alembic commands ###
