"""create initial database schema

Revision ID: e618b7eaaa39
Revises: 
Create Date: 2026-09-04 17:10:16.308028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e618b7eaaa39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('project_members',
    sa.Column('project_member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_member_id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_weekly_reports_project_id'), 'weekly_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    op.create_table('report_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['weekly_reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_report_versions_report_id'), 'report_versions', ['report_id'], unique=False)
    op.create_table('next_week_tasks',
    sa.Column('next_task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['report_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('next_task_id')
    )
    op.create_index(op.f('ix_next_week_tasks_version_id'), 'next_week_tasks', ['version_id'], unique=False)
    op.create_table('report_achievements',
    sa.Column('achievement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_key_achievement', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['report_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_index(op.f('ix_report_achievements_version_id'), 'report_achievements', ['version_id'], unique=False)
    op.create_table('report_blockers',
    sa.Column('blocker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_key_issue', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['report_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id')
    )
    op.create_index(op.f('ix_report_blockers_version_id'), 'report_blockers', ['version_id'], unique=False)
    op.create_table('report_hours',
    sa.Column('hours_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['report_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hours_id')
    )
    op.create_index(op.f('ix_report_hours_version_id'), 'report_hours', ['version_id'], unique=False)
    op.create_table('report_tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('planned_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time_planned', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('time_spent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('deliverable', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['report_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_report_tasks_version_id'), 'report_tasks', ['version_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['weekly_reports.report_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['report_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_comments_report_id'), 'review_comments', ['report_id'], unique=False)
    op.create_index(op.f('ix_review_comments_reviewer_id'), 'review_comments', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_comments_version_id'), 'review_comments', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_version_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_reviewer_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_report_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_report_tasks_version_id'), table_name='report_tasks')
    op.drop_table('report_tasks')
    op.drop_index(op.f('ix_report_hours_version_id'), table_name='report_hours')
    op.drop_table('report_hours')
    op.drop_index(op.f('ix_report_blockers_version_id'), table_name='report_blockers')
    op.drop_table('report_blockers')
    op.drop_index(op.f('ix_report_achievements_version_id'), table_name='report_achievements')
    op.drop_table('report_achievements')
    op.drop_index(op.f('ix_next_week_tasks_version_id'), table_name='next_week_tasks')
    op.drop_table('next_week_tasks')
    op.drop_index(op.f('ix_report_versions_report_id'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_project_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
